### PR TITLE
Reject integers with lengths not between 8 and 14.

### PR DESCRIPTION
**Pull request by guaycuru**
Since we only want to verify GTIN8 through GTIN14: http://www.gs1.org/how-calculate-check-digit-manually.
Otherwise it'd validate invalid gtins like 00000000405713 or 405713.

### CODE REVIEW

**Comment by guaycuru** [comment]
@dominiklessel Please review and merge if you find appropriate.

**Comment by dominiklessel** [comment]
:+1:

**Comment by dominiklessel** [comment]
I also pushed a new version (v2.0.1) to npm.

**Comment by ffranco-daitan** [comment]
Thanks!

**Pull request merged**
